// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiMovies.Data;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230625133145_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("apiMovies.Models.Categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_categoria");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            idcategoria = 1,
                            nombre = "Animación"
                        },
                        new
                        {
                            idcategoria = 2,
                            nombre = "Crimen"
                        },
                        new
                        {
                            idcategoria = 3,
                            nombre = "Familia"
                        },
                        new
                        {
                            idcategoria = 4,
                            nombre = "Misterio"
                        },
                        new
                        {
                            idcategoria = 5,
                            nombre = "Suspenso"
                        },
                        new
                        {
                            idcategoria = 6,
                            nombre = "Terror"
                        },
                        new
                        {
                            idcategoria = 7,
                            nombre = "Romance"
                        },
                        new
                        {
                            idcategoria = 8,
                            nombre = "Drama"
                        },
                        new
                        {
                            idcategoria = 9,
                            nombre = "Ciencia Ficción"
                        },
                        new
                        {
                            idcategoria = 10,
                            nombre = "Acción"
                        });
                });

            modelBuilder.Entity("apiMovies.Models.Pelicula", b =>
                {
                    b.Property<int>("id_pelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("duracion")
                        .HasColumnType("int");

                    b.Property<string>("fotoPelicula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id_pelicula");

                    b.ToTable("Pelicula");

                    b.HasData(
                        new
                        {
                            idpelicula = 1,
                            descripcion = "Un mafioso intenta mantener el control de su imperio criminal mientras protege a su familia.",
                            director = "Francis Ford Coppola",
                            duracion = 175,
                            fotoPelicula = "string",
                            idcategoria = 2,
                            titulo = "El Padrino",
                            year = 1972
                        },
                        new
                        {
                            idpelicula = 2,
                            descripcion = "Un grupo de juguetes cobra vida cuando los humanos no están presentes.",
                            director = "John Lasseter",
                            duracion = 81,
                            fotoPelicula = "string",
                            idcategoria = 1,
                            titulo = "Toy Story",
                            year = 1995
                        },
                        new
                        {
                            idpelicula = 3,
                            descripcion = "Los Vengadores se unen para luchar contra Thanos y restaurar el universo.",
                            director = "Anthony Russo, Joe Russo",
                            duracion = 181,
                            fotoPelicula = "string",
                            idcategoria = 3,
                            titulo = "Avengers: Endgame",
                            year = 2019
                        });
                });

            modelBuilder.Entity("apiMovies.Models.PeliculaUsuario", b =>
                {
                    b.Property<int>("id_pelicula")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("id_pelicula", "id_usuario");

                    b.HasIndex("id_usuario");

                    b.ToTable("PeliculaUsuario");
                });

            modelBuilder.Entity("apiMovies.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("correo_electronico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("fotoUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_usuario");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            idusuario = 1,
                            correoelectronico = "admin@gmail.com",
                            fotoUsuario = "string",
                            nombre = "admin",
                            password = "admin",
                            tipo = "admin"
                        });
                });

            modelBuilder.Entity("apiMovies.Models.PeliculaUsuario", b =>
                {
                    b.HasOne("apiMovies.Models.Pelicula", "Pelicula")
                        .WithMany()
                        .HasForeignKey("id_pelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apiMovies.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
