// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiPelis.Data;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250504231202_migracioninicial")]
    partial class migracioninicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("apiPelis.Models.Categoria", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_categoria"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_categoria");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            id_categoria = 1,
                            nombre = "Animación"
                        },
                        new
                        {
                            id_categoria = 2,
                            nombre = "Crimen"
                        },
                        new
                        {
                            id_categoria = 3,
                            nombre = "Familia"
                        },
                        new
                        {
                            id_categoria = 4,
                            nombre = "Misterio"
                        },
                        new
                        {
                            id_categoria = 5,
                            nombre = "Suspenso"
                        },
                        new
                        {
                            id_categoria = 6,
                            nombre = "Terror"
                        },
                        new
                        {
                            id_categoria = 7,
                            nombre = "Romance"
                        },
                        new
                        {
                            id_categoria = 8,
                            nombre = "Drama"
                        },
                        new
                        {
                            id_categoria = 9,
                            nombre = "Ciencia Ficción"
                        },
                        new
                        {
                            id_categoria = 10,
                            nombre = "Acción"
                        });
                });

            modelBuilder.Entity("apiPelis.Models.Pelicula", b =>
                {
                    b.Property<int>("id_pelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_pelicula"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("duracion")
                        .HasColumnType("int");

                    b.Property<string>("fotoPelicula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("id_pelicula");

                    b.ToTable("Pelicula");

                    b.HasData(
                        new
                        {
                            id_pelicula = 1,
                            descripcion = "Un mafioso intenta mantener el control de su imperio criminal mientras protege a su familia.",
                            director = "Francis Ford Coppola",
                            duracion = 175,
                            fotoPelicula = "string",
                            id_categoria = 2,
                            titulo = "El Padrino",
                            year = 1972
                        },
                        new
                        {
                            id_pelicula = 2,
                            descripcion = "Un grupo de juguetes cobra vida cuando los humanos no están presentes.",
                            director = "John Lasseter",
                            duracion = 81,
                            fotoPelicula = "string",
                            id_categoria = 1,
                            titulo = "Toy Story",
                            year = 1995
                        },
                        new
                        {
                            id_pelicula = 3,
                            descripcion = "Los Vengadores se unen para luchar contra Thanos y restaurar el universo.",
                            director = "Anthony Russo, Joe Russo",
                            duracion = 181,
                            fotoPelicula = "string",
                            id_categoria = 3,
                            titulo = "Avengers: Endgame",
                            year = 2019
                        });
                });

            modelBuilder.Entity("apiPelis.Models.PeliculaUsuario", b =>
                {
                    b.Property<int>("id_pelicula")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("id_pelicula", "id_usuario");

                    b.HasIndex("id_usuario");

                    b.ToTable("PeliculaUsuario");
                });

            modelBuilder.Entity("apiPelis.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("correo_electronico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("fotoUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_usuario");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            id_usuario = 1,
                            correo_electronico = "admin@gmail.com",
                            fotoUsuario = "string",
                            nombre = "admin",
                            password = "admin",
                            tipo = "admin"
                        });
                });

            modelBuilder.Entity("apiPelis.Models.PeliculaUsuario", b =>
                {
                    b.HasOne("apiPelis.Models.Pelicula", "Pelicula")
                        .WithMany()
                        .HasForeignKey("id_pelicula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apiPelis.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
