// <auto-generated />
using ApiMovies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("apiMovies.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Drama"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Action"
                        });
                });

            modelBuilder.Entity("apiMovies.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovieId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1,
                            Description = "Batman faces off against the Joker in Gotham City",
                            Director = "Christopher Nolan",
                            Duration = 152,
                            Title = "The Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 3,
                            Description = "A man with disabilities lives an extraordinary life",
                            Director = "Robert Zemeckis",
                            Duration = 142,
                            Title = "Forrest Gump",
                            Year = 1994
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 3,
                            Description = "A story of crime and redemption in Los Angeles",
                            Director = "Quentin Tarantino",
                            Duration = 154,
                            Title = "Pulp Fiction",
                            Year = 1994
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 3,
                            Description = "A team of thieves invades people's dreams",
                            Director = "Christopher Nolan",
                            Duration = 148,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryId = 3,
                            Description = "An innocent man finds hope in prison",
                            Director = "Frank Darabont",
                            Duration = 142,
                            Title = "The Shawshank Redemption",
                            Year = 1994
                        });
                });

            modelBuilder.Entity("apiMovies.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "john@example.com",
                            Name = "John Doe",
                            Password = "password123",
                            Type = 0
                        },
                        new
                        {
                            UserId = 2,
                            Email = "admin@example.com",
                            Name = "Admin User",
                            Password = "adminpass",
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
